DEFAULT_STOPWORDS = {
    "the", "a", "an", "and", "or", "to", "of", "for", "in", "on", "at", "is", "are", "be",
    "как", "что", "где", "для", "при", "если", "и", "или", "в", "на", "по", "с", "к", "из",
    "это", "этот", "эта", "эти", "его", "ее", "их", "ли", "не", "но", "же", "бы",
}

DEFAULT_SYNONYMS = {
    "зарегистрироваться": ["register", "signup", "sign-up", "registration", "create-account"],
    "регистрация": ["register", "signup", "sign-up", "registration", "create-account"],
    "zaregistrirovatsia": ["register", "signup", "sign-up", "registration", "create-account"],
    "registratsiia": ["register", "signup", "sign-up", "registration", "create-account"],
    "sistema": ["system", "application", "app"],
    "oformit": ["register"],
    "akkaunt": ["account", "registration"],

    "войти": ["login", "signin", "sign-in", "auth"],
    "авторизация": ["auth", "authorization", "login", "signin"],

    "перезапустить": ["restart", "reboot", "bounce"],
    "перезапуск": ["restart", "reboot"],
    "рестарт": ["restart", "reboot"],

    "сервис": ["service", "daemon", "worker", "job", "deployment", "pod"],
    "воркер": ["worker", "consumer", "job"],

    "ошибка": ["error", "failure", "incident"],
    "логи": ["logs", "log", "journal"],
    "очередь": ["queue", "consumer", "worker"],
    "база": ["database", "db", "postgres", "mysql"],
    "бд": ["database", "db", "postgres", "mysql"],
    "проверить": ["check", "verify", "status"],
    "документация": ["docs", "documentation", "guide", "manual"],

    "сбросить": ["reset", "password", "password-reset"],
    "сброс": ["reset", "password", "password-reset"],
    "пароль": ["password", "reset", "password-reset"],
    "sbrosit": ["reset", "password", "password-reset"],
    "sbros": ["reset", "password", "password-reset"],
    "parol": ["password", "reset", "password-reset"],
}

DEFAULT_TECHNICAL_KEYWORDS = {
    "ошибка", "ошибки", "error", "errors", "incident", "outage", "timeout", "timed-out",
    "connection", "refused", "connection-refused", "database", "db", "postgres", "mysql",
    "redis", "база", "бд", "queue", "lag", "worker", "consumer", "очередь", "воркер",
    "api", "gateway", "upstream", "backend", "service", "сервис", "deployment", "deploy",
    "release", "rollback", "релиз", "откат", "pod", "kubernetes", "kubectl", "docker",
    "nginx", "cpu", "memory", "disk", "space", "latency", "лог", "логи", "logs", "metrics",
    "метрики", "401", "403", "404", "500", "502", "503", "504",
}

DEFAULT_DOC_QA_PATTERNS = [
    "как ",
    "где написано",
    "что написано",
    "документац",
    "зарегистрироваться",
    "регистрация",
    "настроить",
    "подключить",
    "создать",
    "сбросить",
    "сброс",
    "пароль",
    "оформить аккаунт",

    "kak ",
    "gde napisano",
    "chto napisano",
    "dokumentats",
    "zaregistrirovatsia",
    "registratsiia",
    "nastroit",
    "podkliuchit",
    "sozdat",
    "sbrosit",
    "sbros",
    "parol",
    "oformit akkaunt",

    "how to",
    "how do i",
    "documentation",
    "docs",
    "register",
    "registration",
    "sign up",
    "signup",
    "password",
    "reset",
]

DEFAULT_INCIDENT_PATTERNS = [
    "сломалось",
    "не работает",
    "упал",
    "падает",
    "инцидент",
    "авария",
    "outage",
    "incident",
    "error rate",
    "после релиза",
    "rollback",
    "откат",
    "timeout",
    "ошибка 500",
    "ошибка 502",
    "ошибка 503",
    "ошибка 504",
    "high cpu",
    "queue lag",
    "disk space",
    "connection refused",
    "too many connections",
]